version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies"
      - npm install

  build:
    commands:
      - echo "Build phase - nothing to compile for Node.js API"

artifacts:
  files:
    - '**/*'
